name: Python Tests

on:
  push:
  pull_request:
    branches:
      - main
      - release
      - v4
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed if you want to push coverage

    steps:
      - name: Run python-action
        uses: rcmdnk/python-action@v3.0.3
        with:
          python-version: "3.11"
          setup-type: uv
          pytest: 1
          pytest-tests-path: tests/
          coverage: 1
          pytest-cov-path: WrenchCL  # Adjust if needed
          pre-commit: 0
